[package]
name = "echo_stuff"
version = "0.1.0"
authors = ["Randy Yeung <h0riz0n.yeung@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
rand = "0.7.3"
structopt = "0.3.11"